### ISSUE TITLE
Missing method - Needs JROSClient update?

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/jrosservices#1]
Hello, having some issues with services since updating to the new JROSClient versions. 
On creating a new service client:
```
     [java] Caused by: java.lang.NoSuchMethodError: 'void id.xfunction.Preconditions.isTrue(boolean, java.lang.String)'
     [java]     at pinorobotics.jros2services.JRos2ServiceClient.onStart(JRos2ServiceClient.java:143) ~[jros2services-2.0.jar:2.0]
```

**Comment by lambdaprime** [comment]
Hi @marlow-fawn ,

Thanks for trying **jrosclient**

Current version of `jros2services` is not compatible with the new version of the client.
We are working on updating it. 
ETA early next week.

Regards,

**Comment by lambdaprime** [comment]
Hi @marlow-fawn ,

The fix is ready in new [version 3](/pinorobotics/jros2services/blob/main/jros2services/release/CHANGELOG.md)
